module.exports = {
  rules: {
    'array-bracket-spacing': [2, 'never'],
    'block-spacing': [2, 'never'],
    'brace-style': 2,
    'camelcase': [2, {properties: 'always'}],
    'comma-spacing': [2, {before: false, after: true}],
    'comma-style': [2, 'last'],
    'computed-property-spacing': [2, 'never'],
    'consistent-this': [2, 'self'],
    'eol-last': 2,
    'func-names': 2,
    'func-style': [2, 'declaration'],
    'id-match': [2, '^[a-z]+([A-Z][a-z]+)*$', {properties: false}],
    'indent': [2, 2, {SwitchCase: 1}],
    'key-spacing': [2, {beforeColon: false, afterColon: true}],
    'keyword-spacing': 2,
    'linebreak-style': 2,
    'lines-around-comment': [
      2,
      {beforeBlockComment: true, beforeLineComment: true}
    ],
    'max-depth': [2, 10],
    'max-len': [2, 80, 4],
    'max-nested-callbacks': [2, 3],
    'max-params': [2, 3],
    'new-cap': 2,
    'new-parens': 2,
    'newline-after-var': [2, 'always'],
    'no-array-constructor': 2,
    'no-bitwise': 2,
    'no-continue': 2,
    'no-inline-comments': 2,
    'no-lonely-if': 2,
    'no-mixed-spaces-and-tabs': [2, 'smart-tabs'],
    'no-multiple-empty-lines': [2, {'max': 1}],
    'no-negated-condition': 2,
    'no-nested-ternary': 2,
    'no-plusplus': 2,
    'no-restricted-syntax': [2, 'FunctionExpression', 'WithStatement'],
    'no-spaced-func': 2,
    'no-ternary': 2,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': [2, {'allow': []}],
    'no-unneeded-ternary': 2,
    'object-curly-spacing': [2, 'never'],
    'one-var': [2, 'never'],
    'operator-linebreak': [2, 'before', {overrides: {'?': 'after'}}],
    'padded-blocks': [2, 'never'],
    'quote-props': [2, 'consistent-as-needed'],
    'quotes': [2, 'single', 'avoid-escape'],
    'semi': [2, 'never'],
    'sort-vars': 2,
    'space-before-blocks': 2,
    'space-before-function-paren': 2,
    'space-in-parens': [2, 'never'],
    'space-infix-ops': [2, {int32Hint: false}],
    'space-unary-ops': [1, {words: true, nonwords: false}],
    'spaced-comment': [2, 'always'],
    'wrap-regex': 2
  }
}
